## Write programs to perform matrices operations
NB: Without using any libruaries such as Numpy

In [205]:
%reset -f
from __future__ import print_function
from __future__ import division

In [206]:
# for easy printing matrix only (not try to cheat!)
from numpy import matrix as mat
from numpy import eye as eye

### 1. Addition of matrices

In [207]:
# Addition of matrices
a = [1,2,3]
b = [4,5,6]
# Addition of a + b in term of matrix

# Note: adding the two list will give you:
print(a+b)

[1, 2, 3, 4, 5, 6]


In [208]:
# logic: adding each element of a vector then add each row(r) of a matrix
def mat_rs(x):
    return [len(row) for row in x] # just to check the dimension of matrix

def mat_add(mat_x, mat_y):    
    if mat_rs(mat_x) != mat_rs(mat_y):
        print('Warning!!! Matrices dimensions are not the same!!!!')
    else:
        return [[mat_x[r][i] + mat_y[r][i] for i, v in enumerate(mat_x[r])] for r, v in enumerate(mat_x)]

In [209]:
# examples
a = [[1,2,3]]
b = [[7,8,9]]
print(mat(mat_add(a, b)))
a = [[1,2,3],[4,5,6],[4,3,5]]
b = [[7,8,9],[5,1,0],[3,4,2]]
print(mat(mat_add(a, b)))

[[ 8 10 12]]
[[ 8 10 12]
 [ 9  6  6]
 [ 7  7  7]]


In [210]:
%%timeit
mat_add(a, b)

The slowest run took 5.94 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.69 µs per loop


In [211]:
%%timeit
mat(a)+mat(b)

100000 loops, best of 3: 12.2 µs per loop


### 2. Scalar multiplication of matrices

In [212]:
# Scalar multiplication of matrices
a = [1,2,3]

# Note: when multiply a list to 3 will give you:
print(a*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [213]:
# logic: just time each elements of a list then loop the rest
def mat_sc_mult(mat, s):
    return [[x*s for x in mat[r]] for r in range(len(mat))]

In [214]:
# # examples
a = [[1,2,3]]
print(mat(mat_sc_mult(a,4)))
a = [[1,2,3],[4,5,6],[4,3,5],[2,3,4]]
print(mat(mat_sc_mult(a,10)))

[[ 4  8 12]]
[[10 20 30]
 [40 50 60]
 [40 30 50]
 [20 30 40]]


In [215]:
%%timeit
mat_sc_mult(a, 10)

The slowest run took 6.24 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.3 µs per loop


In [216]:
%%timeit
mat(a)*10

The slowest run took 13.90 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.84 µs per loop


### 3. Matrix Transpose

In [217]:
# The function is given, but the logic is basically create a list from the nth element of each row
def mat_tran(x):
    return [[row[n] for row in x] for n in range(len(x[0]))]

a = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 0, 1, 2]]
print(mat(mat_tran(a)))

[[1 5 9]
 [2 6 0]
 [3 7 1]
 [4 8 2]]


### 4. Vector Matrix Multiplication

In [218]:
def mat_x_vec(matrix, vector):
    if len(matrix[0]) != len(vector):
        print('Warning! Dimension of the input matrix and vector cannot perform multiplication!!')
    """
    Basically, to do this:
    [[a b c]      [[z]     [[az+bv+cq]
     [d e f]]  x   [v]  =   [dz+ev+fq]]
                   [q]]     
    note that:
    matrix in the form of [[a,b,c],[d,e,f]] 
    vector in the form of [[z],[v],[q]]
    """
    for r in range(len(matrix)):
        return [[sum([matrix[r][i]*vector[i][0] for i, v in enumerate(vector)])]
                for r in range(len(matrix))]

In [219]:
# examples:
a1 = [[1,2,3],[4,5,6]]
a2 = [[7],[8],[9]]
print(mat(mat_x_vec(a1, a2)))

b1 = [[1,2,3,4],[7,8,9,10],[23,45,65,71],[0,2,1,4]]
b2 = [[2],[4],[6],[8]]
print(mat(mat_x_vec(b1, b2)))


[[ 50]
 [122]]
[[  60]
 [ 180]
 [1184]
 [  46]]


In [220]:
# check answer using numpy matrix
print(mat(a1)*mat(a2))
print(mat(b1)*mat(b2))

[[ 50]
 [122]]
[[  60]
 [ 180]
 [1184]
 [  46]]


In [221]:
# error example
c1 = [[1,2,3],[7,8,9],[23,45,65],[0,2,1]]
c2 = [[2],[4],[6],[8]]
print(mat(mat_x_vec(c1, c2)))

Warning! Dimension of the input matrix and vector cannot perform multiplication!!


IndexError: list index out of range

In [222]:
%%timeit
mat_x_vec(b1,b2)

100000 loops, best of 3: 4.19 µs per loop


In [224]:
%%timeit
mat(b1)*mat(b2)

The slowest run took 4.53 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 13 µs per loop


### 5. Matrix Matrix Multiplication

In [225]:
def mat_x_mat(mat1, mat2):
    if len(mat1[0]) != len(mat2):
        print('Warning! Dimension of the input matrix and vector cannot perform ultiplication!!')
    """
    Basically, to do this:
    [[a b c]      [[z x]     [[az+bv+cq ax+by+cw]
     [d e f]]  x   [v y]  =   [dz+ev+fq dx+ey+fw]]
                   [q w]]     
    note that:
    matrix in the form of [[a,b,c],[d,e,f]] 
    vector in the form of [[z,x],[v,y],[q,w]]
    """
    for r in range(len(mat1)):
        return [[sum([mat1[r][i]*mat2[i][c] for i, v in enumerate(mat2)])
                for c in range(len(mat2[0]))] for r in range(len(mat1))]

In [226]:
# exampes
a1 = [[1,2,3],[4,5,6]]
a2 = [[7,3], [8,2], [9,1]]
print(mat(mat_x_mat(a1,a2)))

b1 = [[1,2,3,4],[7,8,9,10],[23,45,65,71],[0,2,1,4]]
b2 = [[2,4,5],[4,7,5],[6,7,7],[8,0,8]]
print(mat(mat_x_mat(b1, b2)))

c1 = [[1,2,3],[4,5,6]]
c2 = [[7],[8],[9]]
print(mat(mat_x_mat(c1, c2)))

[[ 50  10]
 [122  28]]
[[  60   39   68]
 [ 180  147  218]
 [1184  862 1363]
 [  46   21   49]]
[[ 50]
 [122]]


In [227]:
# check answer using numpy matrix
print(mat(a1)*mat(a2))
print(mat(b1)*mat(b2))
print(mat(c1)*mat(c2))

[[ 50  10]
 [122  28]]
[[  60   39   68]
 [ 180  147  218]
 [1184  862 1363]
 [  46   21   49]]
[[ 50]
 [122]]


In [228]:
# error example
d1 = [[1,2,3],[7,8,9],[23,45,65],[0,2,1]]
d2 = [[2,3],[4,4],[6,6],[8,1]]
print(mat(mat_x_mat(d1, d2)))

Warning! Dimension of the input matrix and vector cannot perform ultiplication!!


IndexError: list index out of range

In [229]:
%%timeit
mat_x_mat(b1, b2)

The slowest run took 18.16 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11 µs per loop


In [230]:
%%timeit
mat(b1)*mat(b2)

The slowest run took 4.61 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 13 µs per loop


# PROGRAMMER GOAL
Write test cases and use try/catch in your functions for when matrices are not defined correctly (ie: [ [1,2,3], [4,5] ] is not a matrix.) Or, create a matrix class that also follows these rules.

Write a function that creates an identity matrix. An identity matrix is a matrix where value = 1 if the row and column index are the same, and 0 otherwise. It should build any size identity matrix you want.
Example: iMatrix(4) should be:

In [231]:
i = [[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]
print(mat(i))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [232]:
x = [[1,2,3],[4,5,6],[7,8,9]]
y = [[1,2,3],[4,5,6,7],[7,8,9]]

In [233]:
def mat_check(x):
    for i in range(len(x)):
        if len(x[i]) != len(x[0]):
            print('%s is not a matrix!!' % str(x))
        
mat_check(y)    

[[1, 2, 3], [4, 5, 6, 7], [7, 8, 9]] is not a matrix!!


In [234]:
def id_mat(x):
    # x is the dimension of the identity matrix, i.e. for 3 x 3 identity matrix, x = 3.
    idmat = [([0]*x) for i in range(x)]
    for i in range(x):
        idmat[i][i] = 1
    return(idmat)

In [235]:
%%timeit
id_mat(5) # using self define function

The slowest run took 4.93 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.65 µs per loop


In [237]:
%%timeit
eye(5) # using numpy function

The slowest run took 16.58 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.32 µs per loop
